schema {
    query: Query
    mutation: Mutation
}

type Query {
    Buildings: [Building]
    Building(BuildingID: String!): Building!
}

type Mutation {
    updateBuilding(params: UpdateBuildingInput!): Building!
    updateResident(params: UpdateResidentInput!): Resident!
}
